steps:
- name: python
  entrypoint: pip
  args: ["install", "-U", "poetry"]
- name: python
  volumes:
  - name: 'vol1'
    path: '/temporary'
  entrypoint: poetry
  args: ["export", "-f", "requirements.txt", "--without-hashes", "--output", "/temporary/requirements.txt"]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  volumes:
  - name: 'vol1'
    path: '/temporary'
  entrypoint: 'bash'
  args: ['cp', '/temporary/requirements.txt', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
  env:
    - 'SESSION_SECRET_KEY=${_SESSION_SECRET_KEY}'