steps:
  - name: python
    volumes:
      - name: "vol1"
        path: "/temporary"
    entrypoint: "bash"
    args:
      [
        "-c",
        "pip install poetry && poetry export -f requirements.txt --without-hashes --output /temporary/requirements.txt",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    volumes:
      - name: "vol1"
        path: "/temporary"
    entrypoint: "bash"
    args:
      [
        "-c",
        "cp /temporary/requirements.txt . && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
      ]
    env:
      - "SESSION_SECRET_KEY=${_SESSION_SECRET_KEY}"
timeout: "1600s"
