steps:
- name: 'docker'
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/poetry_image_for_cloud_build:latest", "."]
- name: 'gcr.io/${PROJECT_ID}/poetry_image_for_cloud_build:latest'
  volumes:
  - name: 'vol1'
    path: '/temporary'
  args: ['poetry', 'build', "export", "-f", "requirements.txt", "--without-hashes", "--output", "/temporary/requirements.txt"]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  volumes:
  - name: 'vol1'
    path: '/temporary'
  entrypoint: 'bash'
  args: ['cp', '/temporary/requirements.txt', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  env:
    - 'SESSION_SECRET_KEY=${_SESSION_SECRET_KEY}'
timeout: '1600s'