name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --ignore E501 --show-source --statistics
      - name: Test with pytest
        env:
          SESSION_SECRET_KEY: ${{ $secrets.SESSION_SECRET_KEY }}
        run: |
          poetry run pytest
